workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        PROJECT_PATH: "medlimame.xcodeproj"  # اسم المشروع الخاص بك
        SCHEME: "my-app"  # اسم الـ Scheme الذي تستخدمه
        EXPORT_METHOD: "development"  # تحديد طريقة التوزيع (يمكن أن تكون "app-store" أو "ad-hoc" أو "development")
    steps:
      # Step 1: Install dependencies (if you are using CocoaPods)
      - run:
          name: Install CocoaPods dependencies
          command: |
            gem install cocoapods
            pod install

      # Step 2: Build the app using Xcode
      - xcode-build:
          project: "$PROJECT_PATH"
          scheme: "$SCHEME"
          configuration: "Release"
          export_method: "$EXPORT_METHOD"
          xcargs: "-allowProvisioningUpdates"

      # Step 3: Upload the .ipa to Codemagic artifacts
      - upload-artifact:
          path: "build/ios/ipa/YourApp.ipa"  # استبدل بالمسار الفعلي لـ .ipa
          name: app-ipa
          type: ipa
